# Generated by Django 3.2.7 on 2021-09-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Цікаве про село', max_length=30, verbose_name='Назва')),
                ('anons', models.CharField(default='Анонс про подію', max_length=100, verbose_name='Анонс')),
                ('text', models.TextField(verbose_name='Стаття')),
                ('date', models.DateTimeField(verbose_name='Дата публікації')),
            ],
        ),
    ]
