# Generated by Django 3.2.7 on 2021-09-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='anons',
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(default='Цікаве про село', max_length=100, verbose_name='Назва'),
        ),
    ]
