# Generated by Django 4.0.1 on 2022-01-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220105_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name')),
                ('text', models.TextField(max_length=100, verbose_name='Article')),
                ('date', models.DateTimeField(max_length=100, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'All News',
            },
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
