# Generated by Django 3.1.5 on 2021-04-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Your name ')),
                ('phone', models.IntegerField(max_length=12, verbose_name='Your name')),
            ],
        ),
    ]
