# Generated by Django 3.1.5 on 2021-04-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210418_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.TextField(max_length=12, verbose_name='Your phone'),
        ),
    ]
